# Generated by Django 3.1 on 2023-07-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='User name')),
                ('status', models.CharField(choices=[('1', 'Dildara'), ('2', 'Perfect'), ('3', 'Angel')], max_length=1, verbose_name='Task status')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
