# Generated by Django 3.1 on 2023-07-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20230714_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_request',
            name='status',
            field=models.CharField(choices=[('1', 'Dildara'), ('2', 'Perfect'), ('3', 'Angel'), ('4', 'I Need You')], max_length=1, verbose_name='Song'),
        ),
    ]
