# Generated by Django 3.1 on 2023-07-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20230714_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_request',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='User name'),
        ),
    ]
