# Generated by Django 3.1 on 2023-07-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20230714_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_request',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_request',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user_request',
            name='status',
            field=models.CharField(choices=[('1', 'Dildara'), ('2', 'Perfect'), ('3', 'Angel'), ('4', 'I Need You')], max_length=1, verbose_name='Song'),
        ),
    ]
