# Generated by Django 3.1 on 2023-07-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20230714_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_request',
            old_name='status',
            new_name='song',
        ),
        migrations.RemoveField(
            model_name='user_request',
            name='id',
        ),
        migrations.AddField(
            model_name='user_request',
            name='contact',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True, verbose_name='Contact'),
            preserve_default=False,
        ),
    ]
