# Generated by Django 3.1 on 2023-07-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20230714_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_request',
            name='contact',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Phone'),
        ),
    ]
