# Generated by Django 3.1 on 2023-07-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20230714_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_request',
            name='song',
            field=models.CharField(choices=[('Dildara', 'Dildara'), ('Perfact', 'Perfect'), ('Angel', 'Angel'), ('I need You', 'I Need You')], max_length=100, verbose_name='Song'),
        ),
    ]
